import { Product, Category } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Classic Hardcover Notebook',
    nameBn: 'ক্লাসিক হার্ডকভার নোটবুক',
    category: Category.NOTEBOOKS,
    price: 350,
    originalPrice: 450,
    rating: 4.8,
    image: 'https://picsum.photos/id/24/400/400',
    description: 'A premium quality hardcover notebook for your daily thoughts and lecture notes.',
  },
  {
    id: '2',
    name: 'Gel Pen Set (Black)',
    nameBn: 'জেল পেন সেট (কালো)',
    category: Category.PENS,
    price: 120,
    rating: 4.5,
    image: 'https://picsum.photos/id/366/400/400',
    description: 'Smooth writing gel pens perfect for exams and assignments.',
  },
  {
    id: '3',
    name: 'Professional Sketchbook',
    nameBn: 'প্রফেশনাল স্কেচবুক',
    category: Category.ART,
    price: 550,
    rating: 4.9,
    image: 'https://picsum.photos/id/225/400/400',
    isNew: true,
    description: 'Heavyweight paper suitable for ink, graphite, and charcoal.',
  },
  {
    id: '4',
    name: 'Watercolor Paint Set',
    nameBn: 'জলরং সেট (২৪ কালার)',
    category: Category.ART,
    price: 850,
    originalPrice: 1000,
    rating: 4.7,
    image: 'https://picsum.photos/id/104/400/400',
    description: 'Vibrant watercolors for budding artists and professionals.',
  },
  {
    id: '5',
    name: 'Exam Geometry Box',
    nameBn: 'জ্যামিতি বক্স',
    category: Category.EXAM,
    price: 250,
    rating: 4.6,
    image: 'https://picsum.photos/id/160/400/400',
    description: 'Complete geometry set with compass, divider, and rulers.',
  },
  {
    id: '6',
    name: 'Handmade Dairy',
    nameBn: 'হ্যান্ডমেড ডায়েরি',
    category: Category.GIFTS,
    price: 400,
    rating: 4.9,
    image: 'https://picsum.photos/id/20/400/400',
    isNew: true,
    description: 'Beautifully crafted handmade paper diary with texture.',
  },
  {
    id: '7',
    name: 'Pastel Highlighters',
    nameBn: 'প্যাস্টেল হাইলাইটার',
    category: Category.PENS,
    price: 180,
    rating: 4.8,
    image: 'https://picsum.photos/id/532/400/400',
    description: 'Soft pastel colors that do not bleed through pages.',
  },
  {
    id: '8',
    name: 'Canvas Tote Bag',
    nameBn: 'ক্যানভাস টোট ব্যাগ',
    category: Category.GIFTS,
    price: 320,
    rating: 4.4,
    image: 'https://picsum.photos/id/292/400/400',
    description: 'Eco-friendly tote bag for carrying books and supplies.',
  },
];

export const HERO_TAGLINE_BN = "পড়াশোনা, শিল্প আর আইডিয়ার আখড়া";
export const HERO_TAGLINE_EN = "The hub for studies, art, and ideas.";